#!/usr/bin/env bash
# Run Nango from source (no Docker) + OminiConnect portal together.
#
# Prerequisites (install once on your machine):
#   - Node.js 22+ (see third_party/nango/.nvmrc) and npm
#   - PostgreSQL listening locally (default: 127.0.0.1:5432)
#   - Postgres: one database for Nango, a **second** database for OminiConnect (same server is fine), e.g.:
#       createuser nango 2>/dev/null || true
#       psql -U postgres -c "ALTER USER nango WITH PASSWORD 'nango';" 2>/dev/null || true
#       createdb -O nango nango 2>/dev/null || true
#       createdb -O nango omini_connect_portal 2>/dev/null || true
#     Then set DATABASE_URL=postgres://nango:nango@127.0.0.1:5432/omini_connect_portal in repo-root .env
#   Override Nango URL: export NANGO_DATABASE_URL='postgresql://user:pass@127.0.0.1:5432/nango'
#
# Usage (repo root):
#   cp .env.example .env
#   # Put NANGO_SECRET_KEY in .env after you create an API key in the Nango UI (first successful start).
#   ./scripts/dev_omini_connect_nango_native.sh
#
# First run runs `npm ci` and `npm run ts-build` under third_party/nango (several minutes).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NANGO_DIR="${ROOT}/third_party/nango"

NANGO_APPS_PID=""
cleanup() {
  if [[ -n "${NANGO_APPS_PID}" ]] && kill -0 "${NANGO_APPS_PID}" 2>/dev/null; then
    kill "${NANGO_APPS_PID}" 2>/dev/null || true
    # concurrently spawns children — tear down process group if we created one
    pkill -P "${NANGO_APPS_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

if [[ ! -d "${NANGO_DIR}/packages/server" ]]; then
  echo "Missing Nango sources at ${NANGO_DIR}. Init submodule:"
  echo "  git submodule update --init --recursive"
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required (see third_party/nango/.nvmrc; use nvm/fnm if needed)."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required."
  exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "Rust (cargo) is required for omini-connect-portal."
  exit 1
fi

DB_URL="${NANGO_DATABASE_URL:-postgresql://nango:nango@127.0.0.1:5432/nango}"

if command -v pg_isready >/dev/null 2>&1; then
  # postgresql://user:pass@host:port/dbname
  _rest="${DB_URL#*://}"
  _creds_host="${_rest#*@}"
  _hostport="${_creds_host%%/*}"
  PGHOST="${_hostport%%:*}"
  PGPORT="${_hostport##*:}"
  if [[ "${PGPORT}" == "${_hostport}" ]]; then PGPORT=5432; fi
  if ! pg_isready -h "${PGHOST}" -p "${PGPORT}" >/dev/null 2>&1; then
    echo "PostgreSQL does not accept connections at ${PGHOST}:${PGPORT}."
    echo "Start Postgres, create DB/user (see script header), or set NANGO_DATABASE_URL."
    exit 1
  fi
else
  echo "Tip: install PostgreSQL client tools (pg_isready) for a startup check; continuing anyway."
fi

ensure_nango_env() {
  local env_file="${NANGO_DIR}/.env"
  if [[ -f "${env_file}" ]]; then
    echo "Using existing ${env_file}"
    return
  fi
  echo "Creating ${env_file} for native Postgres..."
  local enc
  enc="$(openssl rand -base64 32)"
  cat >"${env_file}" <<EOF
# Generated by scripts/dev_omini_connect_nango_native.sh — tune as needed.

NANGO_ENCRYPTION_KEY=${enc}

NANGO_DATABASE_URL=${DB_URL}
NANGO_DB_USER=nango
NANGO_DB_PASSWORD=nango
NANGO_DB_HOST=127.0.0.1
NANGO_DB_PORT=5432
NANGO_DB_NAME=nango
NANGO_DB_SSL=false

RECORDS_DATABASE_URL=${DB_URL}

SERVER_PORT=3003
NANGO_SERVER_URL=http://localhost:3003
NANGO_PUBLIC_SERVER_URL=http://localhost:3003

NANGO_PUBLIC_CONNECT_URL=http://localhost:3009
CONNECT_UI_PORT=3009
FLAG_SERVE_CONNECT_UI=true

LOG_LEVEL=info
EOF
  echo "Wrote ${env_file}. Database URL: ${DB_URL}"
}

ensure_nango_env

cd "${NANGO_DIR}"

if [[ ! -d node_modules ]]; then
  echo "Running npm ci in Nango (first time can take several minutes)..."
  npm ci
else
  echo "Using existing third_party/nango/node_modules"
fi

echo "Running npm run ts-build in Nango (one-time compile; can take a few minutes)..."
npm run ts-build

echo "Starting Nango dev processes (server + dashboard + Connect UI) in background..."
npm run dev:watch:web &
NANGO_APPS_PID=$!

cd "${ROOT}"

echo "Waiting for Nango http://localhost:3003/health ..."
for _ in $(seq 1 120); do
  if curl -sf "http://localhost:3003/health" >/dev/null 2>&1; then
    echo "Nango is up."
    break
  fi
  sleep 2
done

if ! curl -sf "http://localhost:3003/health" >/dev/null 2>&1; then
  echo "Nango did not become healthy in time. See logs above, or run manually:"
  echo "  cd third_party/nango && npm run dev:watch:web"
  exit 1
fi

cat <<EOF

----------------------------------------------------------------
Nango (from source): API http://localhost:3003  |  Connect UI http://localhost:3009
Dashboard (Vite):  http://localhost:3000  (if the webapp dev server binds there — check terminal output)

Add to your OminiConnect repo root .env (create from .env.example):
  NANGO_BASE_URL=http://localhost:3003
  NANGO_SECRET_KEY=<create in Nango UI → Environment → API keys>

OminiConnect on Postgres (same host as Nango): use a **separate** database, e.g.
  DATABASE_URL=postgres://nango:nango@127.0.0.1:5432/omini_connect_portal
  (create with: createdb -h 127.0.0.1 -U nango omini_connect_portal)

Stopping Nango: Ctrl+C stops the portal; this script then stops the Nango dev processes.
----------------------------------------------------------------

EOF

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ROOT}/.env"
  set +a
fi

cargo run -p omini-connect-portal
