#!/usr/bin/env bash
# Docker option: Nango via docker-compose in the vendored Nango tree, then OminiConnect portal.
# No Docker: use ./scripts/dev.sh or `make dev`.
#
# Usage:
#   ./scripts/dev_with_nango.sh              # docker up + cargo run -p omini-connect-portal
#   ./scripts/dev_with_nango.sh --nango-only # only start Nango containers
#
# Prerequisites: Docker Desktop (or Docker Engine), git submodule at third_party/nango, openssl.
#
# First-time Nango: creates third_party/nango/.env with a generated NANGO_ENCRYPTION_KEY.
# You still create NANGO_SECRET_KEY in the Nango UI (see script output).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NANGO_DIR="${ROOT}/third_party/nango"
COMPOSE_FILE="${NANGO_DIR}/docker-compose.yaml"

NANGO_ONLY=false
for arg in "$@"; do
  if [[ "${arg}" == "--nango-only" ]]; then
    NANGO_ONLY=true
  fi
done

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  echo "Missing ${COMPOSE_FILE}. Initialize the submodule:"
  echo "  ./scripts/bootstrap_nango_submodule.sh"
  echo "  git submodule update --init --recursive"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is required. Install Docker Desktop or Docker Engine."
  exit 1
fi

# Avoid clashing with a Postgres already bound to host :5432
export NANGO_DB_PORT="${NANGO_DB_PORT:-55432}"

ensure_nango_env() {
  local env_file="${NANGO_DIR}/.env"
  if [[ -f "${env_file}" ]]; then
    echo "Using existing ${env_file}"
    return
  fi
  echo "Creating ${env_file} (first run)..."
  local enc
  enc="$(openssl rand -base64 32)"
  cat >"${env_file}" <<EOF
# Generated by scripts/dev_with_nango.sh — safe to edit. See third_party/nango/.env.example for all options.

NANGO_ENCRYPTION_KEY=${enc}

NANGO_DB_USER=nango
NANGO_DB_PASSWORD=nango
NANGO_DB_NAME=nango
NANGO_DB_SSL=false

RECORDS_DATABASE_URL=postgresql://nango:nango@nango-db:5432/nango

SERVER_PORT=3003
NANGO_SERVER_URL=http://localhost:3003
NANGO_PUBLIC_SERVER_URL=http://localhost:3003

NANGO_PUBLIC_CONNECT_URL=http://localhost:3009
CONNECT_UI_PORT=3009
FLAG_SERVE_CONNECT_UI=true

LOG_LEVEL=info
EOF
  echo "Wrote ${env_file} with a new NANGO_ENCRYPTION_KEY."
}

ensure_nango_env

echo "Starting Nango (Postgres + Redis + nango-server)..."
docker compose --project-directory "${NANGO_DIR}" -f "${COMPOSE_FILE}" up -d

echo "Waiting for Nango API (http://localhost:3003/health)..."
for _ in $(seq 1 90); do
  if curl -sf "http://localhost:3003/health" >/dev/null 2>&1; then
    echo "Nango is up."
    break
  fi
  sleep 2
done

if ! curl -sf "http://localhost:3003/health" >/dev/null 2>&1; then
  echo "Nango did not become healthy in time. Check: docker compose --project-directory ${NANGO_DIR} -f ${COMPOSE_FILE} logs"
  exit 1
fi

cat <<EOF

----------------------------------------------------------------
Nango is running:
  API / dashboard:  http://localhost:3003
  Connect UI:       http://localhost:3009  (also served by server when FLAG_SERVE_CONNECT_UI=true)

Get NANGO_SECRET_KEY for OminiConnect (one-time, copy the secret — it is shown only once):
  1. Open http://localhost:3003 in a browser.
  2. Sign up / sign in (self-hosted default; unless you enabled basic auth in .env).
  3. Use the default Environment (e.g. "dev") or create one.
  4. Go to Environment settings → API Keys (or Integrations / Keys — create a new secret key).
  5. Create a key with scopes that include Connect + proxy usage (default full env scope is fine for dev).
  6. Copy the secret into your OminiConnect repo root .env:
       NANGO_BASE_URL=http://localhost:3003
       NANGO_SECRET_KEY=<paste secret here>

  7. In Nango, add a LinkedIn integration; note its Integration unique key — use it as Provider key in OminiConnect (engine=nango).

Stop Nango later:
  docker compose --project-directory ${NANGO_DIR} -f ${COMPOSE_FILE} down
----------------------------------------------------------------

EOF

if [[ "${NANGO_ONLY}" == true ]]; then
  exit 0
fi

cd "${ROOT}"
if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ROOT}/.env"
  set +a
fi

exec cargo run -p omini-connect-portal
